2022-05-15 15:19:48.180 | INFO     | rsswatch:loop:155 - Початок роботи сканеру новини, на канал @horodysche_channel
2022-05-15 15:19:49.110 | DEBUG    | rsswatch:get_data_xml:109 - XML Отримано!
2022-05-15 15:19:49.153 | DEBUG    | rsswatch:parse_rss:122 - <rss_parser._parser.Parser object at 0x000002CDEE299C30>
2022-05-15 15:19:49.160 | ERROR    | rsswatch:execute_rss_news:131 - An error has been caught in function 'execute_rss_news', process 'MainProcess' (14404), thread 'Thread-1 (loop)' (15332):
Traceback (most recent call last):

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002CDEB4341F0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000002CDEB417EB0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    └ <bound method RssNewsSender.loop of <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\python\core_channel_gor\rsswatch.py", line 160, in loop
    self.execute_rss_news()
    │    └ <function RssNewsSender.execute_rss_news at 0x000002CDEE274EE0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

> File "C:\python\core_channel_gor\rsswatch.py", line 131, in execute_rss_news
    if self.is_unique_news(news):
       │    │              └ FeedItem(title='До уваги осіб, що шукають роботу!', link='https://gormrada.gov.ua/news/1652422345/', publish_date='Fri, 13 Ma...
       │    └ <function RssNewsSender.is_unique_news at 0x000002CDEE274160>
       └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

  File "C:\python\core_channel_gor\rsswatch.py", line 83, in is_unique_news
    self.db_cursor.execute(q)
    │    │         │       └ 'SELECT time_publick FROM news WHERE time_publick = 1652422045'
    │    │         └ <method 'execute' of 'sqlite3.Cursor' objects>
    │    └ <sqlite3.Cursor object at 0x000002CDEDF519C0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 14832 and this is thread id 15332.
2022-05-15 15:19:49.219 | ERROR    | rsswatch:execute_rss_news:131 - An error has been caught in function 'execute_rss_news', process 'MainProcess' (14404), thread 'Thread-1 (loop)' (15332):
Traceback (most recent call last):

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002CDEB4341F0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000002CDEB417EB0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    └ <bound method RssNewsSender.loop of <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\python\core_channel_gor\rsswatch.py", line 160, in loop
    self.execute_rss_news()
    │    └ <function RssNewsSender.execute_rss_news at 0x000002CDEE274EE0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

> File "C:\python\core_channel_gor\rsswatch.py", line 131, in execute_rss_news
    if self.is_unique_news(news):
       │    │              └ FeedItem(title='Державна служба зайнятості\xa0інфромує', link='https://gormrada.gov.ua/news/1652422046/', publish_date='Fri, ...
       │    └ <function RssNewsSender.is_unique_news at 0x000002CDEE274160>
       └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

  File "C:\python\core_channel_gor\rsswatch.py", line 83, in is_unique_news
    self.db_cursor.execute(q)
    │    │         │       └ 'SELECT time_publick FROM news WHERE time_publick = 1652421686'
    │    │         └ <method 'execute' of 'sqlite3.Cursor' objects>
    │    └ <sqlite3.Cursor object at 0x000002CDEDF519C0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 14832 and this is thread id 15332.
2022-05-15 15:19:49.276 | ERROR    | rsswatch:execute_rss_news:131 - An error has been caught in function 'execute_rss_news', process 'MainProcess' (14404), thread 'Thread-1 (loop)' (15332):
Traceback (most recent call last):

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002CDEB4341F0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000002CDEB417EB0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    └ <bound method RssNewsSender.loop of <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\python\core_channel_gor\rsswatch.py", line 160, in loop
    self.execute_rss_news()
    │    └ <function RssNewsSender.execute_rss_news at 0x000002CDEE274EE0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

> File "C:\python\core_channel_gor\rsswatch.py", line 131, in execute_rss_news
    if self.is_unique_news(news):
       │    │              └ FeedItem(title='ОТРИМАЛИ ГУМАНІТАРНУ ДОПОМОГУ З НІМЕЦЬКОГО УЛЬЗЕНА', link='https://gormrada.gov.ua/news/1652072823/', publish...
       │    └ <function RssNewsSender.is_unique_news at 0x000002CDEE274160>
       └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

  File "C:\python\core_channel_gor\rsswatch.py", line 83, in is_unique_news
    self.db_cursor.execute(q)
    │    │         │       └ 'SELECT time_publick FROM news WHERE time_publick = 1652007845'
    │    │         └ <method 'execute' of 'sqlite3.Cursor' objects>
    │    └ <sqlite3.Cursor object at 0x000002CDEDF519C0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 14832 and this is thread id 15332.
2022-05-15 15:19:49.334 | ERROR    | rsswatch:execute_rss_news:131 - An error has been caught in function 'execute_rss_news', process 'MainProcess' (14404), thread 'Thread-1 (loop)' (15332):
Traceback (most recent call last):

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002CDEB4341F0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000002CDEB417EB0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    └ <bound method RssNewsSender.loop of <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\python\core_channel_gor\rsswatch.py", line 160, in loop
    self.execute_rss_news()
    │    └ <function RssNewsSender.execute_rss_news at 0x000002CDEE274EE0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

> File "C:\python\core_channel_gor\rsswatch.py", line 131, in execute_rss_news
    if self.is_unique_news(news):
       │    │              └ FeedItem(title='ВШАНУВАЛИ ПАМ’ЯТЬ ПОЛЕГЛИХ', link='https://gormrada.gov.ua/news/1652073146/', publish_date='Sun, 08 May 2022 ...
       │    └ <function RssNewsSender.is_unique_news at 0x000002CDEE274160>
       └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

  File "C:\python\core_channel_gor\rsswatch.py", line 83, in is_unique_news
    self.db_cursor.execute(q)
    │    │         │       └ 'SELECT time_publick FROM news WHERE time_publick = 1652000906'
    │    │         └ <method 'execute' of 'sqlite3.Cursor' objects>
    │    └ <sqlite3.Cursor object at 0x000002CDEDF519C0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 14832 and this is thread id 15332.
2022-05-15 15:19:49.487 | ERROR    | rsswatch:execute_rss_news:131 - An error has been caught in function 'execute_rss_news', process 'MainProcess' (14404), thread 'Thread-1 (loop)' (15332):
Traceback (most recent call last):

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002CDEB4341F0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000002CDEB417EB0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    └ <bound method RssNewsSender.loop of <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\python\core_channel_gor\rsswatch.py", line 160, in loop
    self.execute_rss_news()
    │    └ <function RssNewsSender.execute_rss_news at 0x000002CDEE274EE0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

> File "C:\python\core_channel_gor\rsswatch.py", line 131, in execute_rss_news
    if self.is_unique_news(news):
       │    │              └ FeedItem(title='06 травня 2022 року Президентом України підписано Закон України «Про внесення змін до деяких законів України ...
       │    └ <function RssNewsSender.is_unique_news at 0x000002CDEE274160>
       └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

  File "C:\python\core_channel_gor\rsswatch.py", line 83, in is_unique_news
    self.db_cursor.execute(q)
    │    │         │       └ 'SELECT time_publick FROM news WHERE time_publick = 1651903948'
    │    │         └ <method 'execute' of 'sqlite3.Cursor' objects>
    │    └ <sqlite3.Cursor object at 0x000002CDEDF519C0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 14832 and this is thread id 15332.
2022-05-15 15:19:49.547 | ERROR    | rsswatch:execute_rss_news:131 - An error has been caught in function 'execute_rss_news', process 'MainProcess' (14404), thread 'Thread-1 (loop)' (15332):
Traceback (most recent call last):

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002CDEB4341F0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000002CDEB417EB0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    └ <bound method RssNewsSender.loop of <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\python\core_channel_gor\rsswatch.py", line 160, in loop
    self.execute_rss_news()
    │    └ <function RssNewsSender.execute_rss_news at 0x000002CDEE274EE0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

> File "C:\python\core_channel_gor\rsswatch.py", line 131, in execute_rss_news
    if self.is_unique_news(news):
       │    │              └ FeedItem(title='8 травня ми відзначаємо День пам’яті та примирення. На жаль, цьогоріч він минає під звуки сирен, що сповіщают...
       │    └ <function RssNewsSender.is_unique_news at 0x000002CDEE274160>
       └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

  File "C:\python\core_channel_gor\rsswatch.py", line 83, in is_unique_news
    self.db_cursor.execute(q)
    │    │         │       └ 'SELECT time_publick FROM news WHERE time_publick = 1651850453'
    │    │         └ <method 'execute' of 'sqlite3.Cursor' objects>
    │    └ <sqlite3.Cursor object at 0x000002CDEDF519C0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 14832 and this is thread id 15332.
2022-05-15 15:19:49.608 | ERROR    | rsswatch:execute_rss_news:131 - An error has been caught in function 'execute_rss_news', process 'MainProcess' (14404), thread 'Thread-1 (loop)' (15332):
Traceback (most recent call last):

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002CDEB4341F0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000002CDEB417EB0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    └ <bound method RssNewsSender.loop of <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\python\core_channel_gor\rsswatch.py", line 160, in loop
    self.execute_rss_news()
    │    └ <function RssNewsSender.execute_rss_news at 0x000002CDEE274EE0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

> File "C:\python\core_channel_gor\rsswatch.py", line 131, in execute_rss_news
    if self.is_unique_news(news):
       │    │              └ FeedItem(title='Будьте уважними при пошуку роботи!', link='https://gormrada.gov.ua/news/1651821664/', publish_date='Fri, 06 M...
       │    └ <function RssNewsSender.is_unique_news at 0x000002CDEE274160>
       └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

  File "C:\python\core_channel_gor\rsswatch.py", line 83, in is_unique_news
    self.db_cursor.execute(q)
    │    │         │       └ 'SELECT time_publick FROM news WHERE time_publick = 1651821544'
    │    │         └ <method 'execute' of 'sqlite3.Cursor' objects>
    │    └ <sqlite3.Cursor object at 0x000002CDEDF519C0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 14832 and this is thread id 15332.
2022-05-15 15:19:49.707 | ERROR    | rsswatch:execute_rss_news:131 - An error has been caught in function 'execute_rss_news', process 'MainProcess' (14404), thread 'Thread-1 (loop)' (15332):
Traceback (most recent call last):

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002CDEB4341F0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000002CDEB417EB0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    └ <bound method RssNewsSender.loop of <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\python\core_channel_gor\rsswatch.py", line 160, in loop
    self.execute_rss_news()
    │    └ <function RssNewsSender.execute_rss_news at 0x000002CDEE274EE0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

> File "C:\python\core_channel_gor\rsswatch.py", line 131, in execute_rss_news
    if self.is_unique_news(news):
       │    │              └ FeedItem(title='ОТРИМАЛИ ГУМАНІТАРНУ ДОПОМОГУ', link='https://gormrada.gov.ua/news/1651817738/', publish_date='Thu, 05 May 20...
       │    └ <function RssNewsSender.is_unique_news at 0x000002CDEE274160>
       └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

  File "C:\python\core_channel_gor\rsswatch.py", line 83, in is_unique_news
    self.db_cursor.execute(q)
    │    │         │       └ 'SELECT time_publick FROM news WHERE time_publick = 1651767098'
    │    │         └ <method 'execute' of 'sqlite3.Cursor' objects>
    │    └ <sqlite3.Cursor object at 0x000002CDEDF519C0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 14832 and this is thread id 15332.
2022-05-15 15:19:49.763 | ERROR    | rsswatch:execute_rss_news:131 - An error has been caught in function 'execute_rss_news', process 'MainProcess' (14404), thread 'Thread-1 (loop)' (15332):
Traceback (most recent call last):

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002CDEB4341F0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000002CDEB417EB0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    └ <bound method RssNewsSender.loop of <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\python\core_channel_gor\rsswatch.py", line 160, in loop
    self.execute_rss_news()
    │    └ <function RssNewsSender.execute_rss_news at 0x000002CDEE274EE0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

> File "C:\python\core_channel_gor\rsswatch.py", line 131, in execute_rss_news
    if self.is_unique_news(news):
       │    │              └ FeedItem(title='Звертаємо увагу!', link='https://gormrada.gov.ua/news/1651757131/', publish_date='Thu, 05 May 2022 16:23:13 +...
       │    └ <function RssNewsSender.is_unique_news at 0x000002CDEE274160>
       └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

  File "C:\python\core_channel_gor\rsswatch.py", line 83, in is_unique_news
    self.db_cursor.execute(q)
    │    │         │       └ 'SELECT time_publick FROM news WHERE time_publick = 1651756993'
    │    │         └ <method 'execute' of 'sqlite3.Cursor' objects>
    │    └ <sqlite3.Cursor object at 0x000002CDEDF519C0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 14832 and this is thread id 15332.
2022-05-15 15:19:49.821 | ERROR    | rsswatch:execute_rss_news:131 - An error has been caught in function 'execute_rss_news', process 'MainProcess' (14404), thread 'Thread-1 (loop)' (15332):
Traceback (most recent call last):

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002CDEB4341F0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000002CDEB417EB0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    └ <bound method RssNewsSender.loop of <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\python\core_channel_gor\rsswatch.py", line 160, in loop
    self.execute_rss_news()
    │    └ <function RssNewsSender.execute_rss_news at 0x000002CDEE274EE0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

> File "C:\python\core_channel_gor\rsswatch.py", line 131, in execute_rss_news
    if self.is_unique_news(news):
       │    │              └ FeedItem(title='СТАН ВИРОБНИЧОГО ТРАВМАТИЗМУ ЗА І КВАРТАЛ 2022 РОКУ', link='https://gormrada.gov.ua/news/1651577024/', publis...
       │    └ <function RssNewsSender.is_unique_news at 0x000002CDEE274160>
       └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

  File "C:\python\core_channel_gor\rsswatch.py", line 83, in is_unique_news
    self.db_cursor.execute(q)
    │    │         │       └ 'SELECT time_publick FROM news WHERE time_publick = 1651576964'
    │    │         └ <method 'execute' of 'sqlite3.Cursor' objects>
    │    └ <sqlite3.Cursor object at 0x000002CDEDF519C0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 14832 and this is thread id 15332.
2022-05-15 15:19:49.920 | ERROR    | rsswatch:execute_rss_news:131 - An error has been caught in function 'execute_rss_news', process 'MainProcess' (14404), thread 'Thread-1 (loop)' (15332):
Traceback (most recent call last):

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002CDEB4341F0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000002CDEB417EB0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    └ <bound method RssNewsSender.loop of <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\python\core_channel_gor\rsswatch.py", line 160, in loop
    self.execute_rss_news()
    │    └ <function RssNewsSender.execute_rss_news at 0x000002CDEE274EE0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

> File "C:\python\core_channel_gor\rsswatch.py", line 131, in execute_rss_news
    if self.is_unique_news(news):
       │    │              └ FeedItem(title='Інформаційно-аналітична довідка про роботу із зверненнями громадян за І квартал 2022 року', link='https://gor...
       │    └ <function RssNewsSender.is_unique_news at 0x000002CDEE274160>
       └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

  File "C:\python\core_channel_gor\rsswatch.py", line 83, in is_unique_news
    self.db_cursor.execute(q)
    │    │         │       └ 'SELECT time_publick FROM news WHERE time_publick = 1651561639'
    │    │         └ <method 'execute' of 'sqlite3.Cursor' objects>
    │    └ <sqlite3.Cursor object at 0x000002CDEDF519C0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 14832 and this is thread id 15332.
2022-05-15 15:19:49.979 | ERROR    | rsswatch:execute_rss_news:131 - An error has been caught in function 'execute_rss_news', process 'MainProcess' (14404), thread 'Thread-1 (loop)' (15332):
Traceback (most recent call last):

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002CDEB4341F0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000002CDEB417EB0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    └ <bound method RssNewsSender.loop of <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\python\core_channel_gor\rsswatch.py", line 160, in loop
    self.execute_rss_news()
    │    └ <function RssNewsSender.execute_rss_news at 0x000002CDEE274EE0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

> File "C:\python\core_channel_gor\rsswatch.py", line 131, in execute_rss_news
    if self.is_unique_news(news):
       │    │              └ FeedItem(title='ОГОЛОШЕННЯ ПРО ПРОВЕДЕННЯ КОНКУРСУ З ПЕРЕВЕЗЕННЯ ПАСАЖИРІВ НА МІСЬКОМУ ТА ПРИМІСЬКИХ АВТОБУСНИХ МАРШРУТАХ ЗАГ...
       │    └ <function RssNewsSender.is_unique_news at 0x000002CDEE274160>
       └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

  File "C:\python\core_channel_gor\rsswatch.py", line 83, in is_unique_news
    self.db_cursor.execute(q)
    │    │         │       └ 'SELECT time_publick FROM news WHERE time_publick = 1651493410'
    │    │         └ <method 'execute' of 'sqlite3.Cursor' objects>
    │    └ <sqlite3.Cursor object at 0x000002CDEDF519C0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 14832 and this is thread id 15332.
2022-05-15 15:19:50.036 | ERROR    | rsswatch:execute_rss_news:131 - An error has been caught in function 'execute_rss_news', process 'MainProcess' (14404), thread 'Thread-1 (loop)' (15332):
Traceback (most recent call last):

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002CDEB4341F0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000002CDEB417EB0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    └ <bound method RssNewsSender.loop of <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\python\core_channel_gor\rsswatch.py", line 160, in loop
    self.execute_rss_news()
    │    └ <function RssNewsSender.execute_rss_news at 0x000002CDEE274EE0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

> File "C:\python\core_channel_gor\rsswatch.py", line 131, in execute_rss_news
    if self.is_unique_news(news):
       │    │              └ FeedItem(title='Умови конкурсу з перевезення пасажирів', link='https://gormrada.gov.ua/news/1651493616/', publish_date='Mon, ...
       │    └ <function RssNewsSender.is_unique_news at 0x000002CDEE274160>
       └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

  File "C:\python\core_channel_gor\rsswatch.py", line 83, in is_unique_news
    self.db_cursor.execute(q)
    │    │         │       └ 'SELECT time_publick FROM news WHERE time_publick = 1651492896'
    │    │         └ <method 'execute' of 'sqlite3.Cursor' objects>
    │    └ <sqlite3.Cursor object at 0x000002CDEDF519C0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 14832 and this is thread id 15332.
2022-05-15 15:19:50.154 | ERROR    | rsswatch:execute_rss_news:131 - An error has been caught in function 'execute_rss_news', process 'MainProcess' (14404), thread 'Thread-1 (loop)' (15332):
Traceback (most recent call last):

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002CDEB4341F0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000002CDEB417EB0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    └ <bound method RssNewsSender.loop of <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\python\core_channel_gor\rsswatch.py", line 160, in loop
    self.execute_rss_news()
    │    └ <function RssNewsSender.execute_rss_news at 0x000002CDEE274EE0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

> File "C:\python\core_channel_gor\rsswatch.py", line 131, in execute_rss_news
    if self.is_unique_news(news):
       │    │              └ FeedItem(title='Рішення Про конкурс з перевезення пасажирів', link='https://gormrada.gov.ua/news/1651493816/', publish_date='...
       │    └ <function RssNewsSender.is_unique_news at 0x000002CDEE274160>
       └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

  File "C:\python\core_channel_gor\rsswatch.py", line 83, in is_unique_news
    self.db_cursor.execute(q)
    │    │         │       └ 'SELECT time_publick FROM news WHERE time_publick = 1651492841'
    │    │         └ <method 'execute' of 'sqlite3.Cursor' objects>
    │    └ <sqlite3.Cursor object at 0x000002CDEDF519C0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 14832 and this is thread id 15332.
2022-05-15 15:19:50.211 | ERROR    | rsswatch:execute_rss_news:131 - An error has been caught in function 'execute_rss_news', process 'MainProcess' (14404), thread 'Thread-1 (loop)' (15332):
Traceback (most recent call last):

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002CDEB4341F0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000002CDEB417EB0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    └ <bound method RssNewsSender.loop of <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\python\core_channel_gor\rsswatch.py", line 160, in loop
    self.execute_rss_news()
    │    └ <function RssNewsSender.execute_rss_news at 0x000002CDEE274EE0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

> File "C:\python\core_channel_gor\rsswatch.py", line 131, in execute_rss_news
    if self.is_unique_news(news):
       │    │              └ FeedItem(title='УВАГА! Важлива інформація', link='https://gormrada.gov.ua/news/1651477563/', publish_date='Sat, 30 Apr 2022 1...
       │    └ <function RssNewsSender.is_unique_news at 0x000002CDEE274160>
       └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

  File "C:\python\core_channel_gor\rsswatch.py", line 83, in is_unique_news
    self.db_cursor.execute(q)
    │    │         │       └ 'SELECT time_publick FROM news WHERE time_publick = 1651304654'
    │    │         └ <method 'execute' of 'sqlite3.Cursor' objects>
    │    └ <sqlite3.Cursor object at 0x000002CDEDF519C0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 14832 and this is thread id 15332.
2022-05-15 15:19:50.270 | ERROR    | rsswatch:execute_rss_news:131 - An error has been caught in function 'execute_rss_news', process 'MainProcess' (14404), thread 'Thread-1 (loop)' (15332):
Traceback (most recent call last):

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002CDEB4341F0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000002CDEB417EB0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    └ <bound method RssNewsSender.loop of <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\python\core_channel_gor\rsswatch.py", line 160, in loop
    self.execute_rss_news()
    │    └ <function RssNewsSender.execute_rss_news at 0x000002CDEE274EE0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

> File "C:\python\core_channel_gor\rsswatch.py", line 131, in execute_rss_news
    if self.is_unique_news(news):
       │    │              └ FeedItem(title='НА ЧЕРГОВІЙ СЕСІЇ МІСЬКОЇ РАДИ ПРИЙНЯЛИ ПРОГРАМУ ПІДТРИМКИ ВІЙСЬКОВИХ', link='https://gormrada.gov.ua/news/16...
       │    └ <function RssNewsSender.is_unique_news at 0x000002CDEE274160>
       └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

  File "C:\python\core_channel_gor\rsswatch.py", line 83, in is_unique_news
    self.db_cursor.execute(q)
    │    │         │       └ 'SELECT time_publick FROM news WHERE time_publick = 1651147890'
    │    │         └ <method 'execute' of 'sqlite3.Cursor' objects>
    │    └ <sqlite3.Cursor object at 0x000002CDEDF519C0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 14832 and this is thread id 15332.
2022-05-15 15:19:50.368 | ERROR    | rsswatch:execute_rss_news:131 - An error has been caught in function 'execute_rss_news', process 'MainProcess' (14404), thread 'Thread-1 (loop)' (15332):
Traceback (most recent call last):

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002CDEB4341F0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000002CDEB417EB0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    └ <bound method RssNewsSender.loop of <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\python\core_channel_gor\rsswatch.py", line 160, in loop
    self.execute_rss_news()
    │    └ <function RssNewsSender.execute_rss_news at 0x000002CDEE274EE0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

> File "C:\python\core_channel_gor\rsswatch.py", line 131, in execute_rss_news
    if self.is_unique_news(news):
       │    │              └ FeedItem(title='«ЧОРНОБИЛЬ –ПОПЕРЕДЖЕННЯ, НАБАТ!»', link='https://gormrada.gov.ua/news/1651038506/', publish_date='Tue, 26 Ap...
       │    └ <function RssNewsSender.is_unique_news at 0x000002CDEE274160>
       └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

  File "C:\python\core_channel_gor\rsswatch.py", line 83, in is_unique_news
    self.db_cursor.execute(q)
    │    │         │       └ 'SELECT time_publick FROM news WHERE time_publick = 1650969986'
    │    │         └ <method 'execute' of 'sqlite3.Cursor' objects>
    │    └ <sqlite3.Cursor object at 0x000002CDEDF519C0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 14832 and this is thread id 15332.
2022-05-15 15:19:50.428 | ERROR    | rsswatch:execute_rss_news:131 - An error has been caught in function 'execute_rss_news', process 'MainProcess' (14404), thread 'Thread-1 (loop)' (15332):
Traceback (most recent call last):

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002CDEB4341F0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000002CDEB417EB0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    └ <bound method RssNewsSender.loop of <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\python\core_channel_gor\rsswatch.py", line 160, in loop
    self.execute_rss_news()
    │    └ <function RssNewsSender.execute_rss_news at 0x000002CDEE274EE0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

> File "C:\python\core_channel_gor\rsswatch.py", line 131, in execute_rss_news
    if self.is_unique_news(news):
       │    │              └ FeedItem(title='Внесок кожного громадянина - є вагомою складовою для пришвидшення перемоги над ворогом!', link='https://gormr...
       │    └ <function RssNewsSender.is_unique_news at 0x000002CDEE274160>
       └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

  File "C:\python\core_channel_gor\rsswatch.py", line 83, in is_unique_news
    self.db_cursor.execute(q)
    │    │         │       └ 'SELECT time_publick FROM news WHERE time_publick = 1650956026'
    │    │         └ <method 'execute' of 'sqlite3.Cursor' objects>
    │    └ <sqlite3.Cursor object at 0x000002CDEDF519C0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 14832 and this is thread id 15332.
2022-05-15 15:19:50.484 | ERROR    | rsswatch:execute_rss_news:131 - An error has been caught in function 'execute_rss_news', process 'MainProcess' (14404), thread 'Thread-1 (loop)' (15332):
Traceback (most recent call last):

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002CDEB4341F0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000002CDEB417EB0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    └ <bound method RssNewsSender.loop of <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\python\core_channel_gor\rsswatch.py", line 160, in loop
    self.execute_rss_news()
    │    └ <function RssNewsSender.execute_rss_news at 0x000002CDEE274EE0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

> File "C:\python\core_channel_gor\rsswatch.py", line 131, in execute_rss_news
    if self.is_unique_news(news):
       │    │              └ FeedItem(title='Запишись в добровольці з цивільного захисту – допоможи країні!', link='https://gormrada.gov.ua/news/165103863...
       │    └ <function RssNewsSender.is_unique_news at 0x000002CDEE274160>
       └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

  File "C:\python\core_channel_gor\rsswatch.py", line 83, in is_unique_news
    self.db_cursor.execute(q)
    │    │         │       └ 'SELECT time_publick FROM news WHERE time_publick = 1650898170'
    │    │         └ <method 'execute' of 'sqlite3.Cursor' objects>
    │    └ <sqlite3.Cursor object at 0x000002CDEDF519C0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 14832 and this is thread id 15332.
2022-05-15 15:19:50.583 | ERROR    | rsswatch:execute_rss_news:131 - An error has been caught in function 'execute_rss_news', process 'MainProcess' (14404), thread 'Thread-1 (loop)' (15332):
Traceback (most recent call last):

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002CDEB4341F0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000002CDEB417EB0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    └ <bound method RssNewsSender.loop of <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\python\core_channel_gor\rsswatch.py", line 160, in loop
    self.execute_rss_news()
    │    └ <function RssNewsSender.execute_rss_news at 0x000002CDEE274EE0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

> File "C:\python\core_channel_gor\rsswatch.py", line 131, in execute_rss_news
    if self.is_unique_news(news):
       │    │              └ FeedItem(title='ЗВІТУЄМОСЯ ПРО РУХ ГУМАНІТАРНОЇ ДОПОМОГИ', link='https://gormrada.gov.ua/news/1650885260/', publish_date='Mon...
       │    └ <function RssNewsSender.is_unique_news at 0x000002CDEE274160>
       └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

  File "C:\python\core_channel_gor\rsswatch.py", line 83, in is_unique_news
    self.db_cursor.execute(q)
    │    │         │       └ 'SELECT time_publick FROM news WHERE time_publick = 1650885200'
    │    │         └ <method 'execute' of 'sqlite3.Cursor' objects>
    │    └ <sqlite3.Cursor object at 0x000002CDEDF519C0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 14832 and this is thread id 15332.
2022-05-15 15:19:50.644 | ERROR    | rsswatch:execute_rss_news:131 - An error has been caught in function 'execute_rss_news', process 'MainProcess' (14404), thread 'Thread-1 (loop)' (15332):
Traceback (most recent call last):

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002CDEB4341F0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000002CDEB417EB0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    └ <bound method RssNewsSender.loop of <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\python\core_channel_gor\rsswatch.py", line 160, in loop
    self.execute_rss_news()
    │    └ <function RssNewsSender.execute_rss_news at 0x000002CDEE274EE0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

> File "C:\python\core_channel_gor\rsswatch.py", line 131, in execute_rss_news
    if self.is_unique_news(news):
       │    │              └ FeedItem(title='Важлива інформація', link='https://gormrada.gov.ua/news/1650625791/', publish_date='Fri, 22 Apr 2022 14:06:19...
       │    └ <function RssNewsSender.is_unique_news at 0x000002CDEE274160>
       └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

  File "C:\python\core_channel_gor\rsswatch.py", line 83, in is_unique_news
    self.db_cursor.execute(q)
    │    │         │       └ 'SELECT time_publick FROM news WHERE time_publick = 1650625579'
    │    │         └ <method 'execute' of 'sqlite3.Cursor' objects>
    │    └ <sqlite3.Cursor object at 0x000002CDEDF519C0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 14832 and this is thread id 15332.
2022-05-15 15:19:50.707 | ERROR    | rsswatch:execute_rss_news:131 - An error has been caught in function 'execute_rss_news', process 'MainProcess' (14404), thread 'Thread-1 (loop)' (15332):
Traceback (most recent call last):

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002CDEB4341F0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000002CDEB417EB0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    └ <bound method RssNewsSender.loop of <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\python\core_channel_gor\rsswatch.py", line 160, in loop
    self.execute_rss_news()
    │    └ <function RssNewsSender.execute_rss_news at 0x000002CDEE274EE0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

> File "C:\python\core_channel_gor\rsswatch.py", line 131, in execute_rss_news
    if self.is_unique_news(news):
       │    │              └ FeedItem(title='ВАНТАЖ ВИРУШИВ ДО МІСЦЯ ПРИЗНАЧЕННЯ: ВЕЛИКДЕНЬ БУДЕ СИМВОЛІЧНИМ', link='https://gormrada.gov.ua/news/16506092...
       │    └ <function RssNewsSender.is_unique_news at 0x000002CDEE274160>
       └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

  File "C:\python\core_channel_gor\rsswatch.py", line 83, in is_unique_news
    self.db_cursor.execute(q)
    │    │         │       └ 'SELECT time_publick FROM news WHERE time_publick = 1650609213'
    │    │         └ <method 'execute' of 'sqlite3.Cursor' objects>
    │    └ <sqlite3.Cursor object at 0x000002CDEDF519C0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 14832 and this is thread id 15332.
2022-05-15 15:19:50.829 | ERROR    | rsswatch:execute_rss_news:131 - An error has been caught in function 'execute_rss_news', process 'MainProcess' (14404), thread 'Thread-1 (loop)' (15332):
Traceback (most recent call last):

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002CDEB4341F0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000002CDEB417EB0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    └ <bound method RssNewsSender.loop of <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\python\core_channel_gor\rsswatch.py", line 160, in loop
    self.execute_rss_news()
    │    └ <function RssNewsSender.execute_rss_news at 0x000002CDEE274EE0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

> File "C:\python\core_channel_gor\rsswatch.py", line 131, in execute_rss_news
    if self.is_unique_news(news):
       │    │              └ FeedItem(title='КУЛЬТУРА: НОВІ НАПРЯМКИ РОБОТИ В УМОВАХ ВІЙНИ', link='https://gormrada.gov.ua/news/1650536298/', publish_date...
       │    └ <function RssNewsSender.is_unique_news at 0x000002CDEE274160>
       └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

  File "C:\python\core_channel_gor\rsswatch.py", line 83, in is_unique_news
    self.db_cursor.execute(q)
    │    │         │       └ 'SELECT time_publick FROM news WHERE time_publick = 1650536238'
    │    │         └ <method 'execute' of 'sqlite3.Cursor' objects>
    │    └ <sqlite3.Cursor object at 0x000002CDEDF519C0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 14832 and this is thread id 15332.
2022-05-15 15:19:50.893 | ERROR    | rsswatch:execute_rss_news:131 - An error has been caught in function 'execute_rss_news', process 'MainProcess' (14404), thread 'Thread-1 (loop)' (15332):
Traceback (most recent call last):

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002CDEB4341F0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000002CDEB417EB0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    └ <bound method RssNewsSender.loop of <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\python\core_channel_gor\rsswatch.py", line 160, in loop
    self.execute_rss_news()
    │    └ <function RssNewsSender.execute_rss_news at 0x000002CDEE274EE0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

> File "C:\python\core_channel_gor\rsswatch.py", line 131, in execute_rss_news
    if self.is_unique_news(news):
       │    │              └ FeedItem(title='У ЄДНОСТІ – НАША СИЛА', link='https://gormrada.gov.ua/news/1650517611/', publish_date='Wed, 20 Apr 2022 11:05...
       │    └ <function RssNewsSender.is_unique_news at 0x000002CDEE274160>
       └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

  File "C:\python\core_channel_gor\rsswatch.py", line 83, in is_unique_news
    self.db_cursor.execute(q)
    │    │         │       └ 'SELECT time_publick FROM news WHERE time_publick = 1650441923'
    │    │         └ <method 'execute' of 'sqlite3.Cursor' objects>
    │    └ <sqlite3.Cursor object at 0x000002CDEDF519C0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 14832 and this is thread id 15332.
2022-05-15 15:19:50.958 | ERROR    | rsswatch:execute_rss_news:131 - An error has been caught in function 'execute_rss_news', process 'MainProcess' (14404), thread 'Thread-1 (loop)' (15332):
Traceback (most recent call last):

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002CDEB4341F0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000002CDEB417EB0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    └ <bound method RssNewsSender.loop of <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\python\core_channel_gor\rsswatch.py", line 160, in loop
    self.execute_rss_news()
    │    └ <function RssNewsSender.execute_rss_news at 0x000002CDEE274EE0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

> File "C:\python\core_channel_gor\rsswatch.py", line 131, in execute_rss_news
    if self.is_unique_news(news):
       │    │              └ FeedItem(title='Чат-бот для пошуку людей', link='https://gormrada.gov.ua/news/1650441949/', publish_date='Wed, 20 Apr 2022 11...
       │    └ <function RssNewsSender.is_unique_news at 0x000002CDEE274160>
       └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

  File "C:\python\core_channel_gor\rsswatch.py", line 83, in is_unique_news
    self.db_cursor.execute(q)
    │    │         │       └ 'SELECT time_publick FROM news WHERE time_publick = 1650441829'
    │    │         └ <method 'execute' of 'sqlite3.Cursor' objects>
    │    └ <sqlite3.Cursor object at 0x000002CDEDF519C0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 14832 and this is thread id 15332.
2022-05-15 15:19:51.068 | ERROR    | rsswatch:execute_rss_news:131 - An error has been caught in function 'execute_rss_news', process 'MainProcess' (14404), thread 'Thread-1 (loop)' (15332):
Traceback (most recent call last):

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002CDEB4341F0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000002CDEB417EB0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    └ <bound method RssNewsSender.loop of <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\python\core_channel_gor\rsswatch.py", line 160, in loop
    self.execute_rss_news()
    │    └ <function RssNewsSender.execute_rss_news at 0x000002CDEE274EE0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

> File "C:\python\core_channel_gor\rsswatch.py", line 131, in execute_rss_news
    if self.is_unique_news(news):
       │    │              └ FeedItem(title='УСЕ БУДЕ УКРАЇНА!', link='https://gormrada.gov.ua/news/1650443918/', publish_date='Tue, 19 Apr 2022 11:38:55 ...
       │    └ <function RssNewsSender.is_unique_news at 0x000002CDEE274160>
       └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

  File "C:\python\core_channel_gor\rsswatch.py", line 83, in is_unique_news
    self.db_cursor.execute(q)
    │    │         │       └ 'SELECT time_publick FROM news WHERE time_publick = 1650357535'
    │    │         └ <method 'execute' of 'sqlite3.Cursor' objects>
    │    └ <sqlite3.Cursor object at 0x000002CDEDF519C0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 14832 and this is thread id 15332.
2022-05-15 15:19:51.131 | ERROR    | rsswatch:execute_rss_news:131 - An error has been caught in function 'execute_rss_news', process 'MainProcess' (14404), thread 'Thread-1 (loop)' (15332):
Traceback (most recent call last):

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002CDEB4341F0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000002CDEB417EB0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    └ <bound method RssNewsSender.loop of <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\python\core_channel_gor\rsswatch.py", line 160, in loop
    self.execute_rss_news()
    │    └ <function RssNewsSender.execute_rss_news at 0x000002CDEE274EE0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

> File "C:\python\core_channel_gor\rsswatch.py", line 131, in execute_rss_news
    if self.is_unique_news(news):
       │    │              └ FeedItem(title='ДО УВАГИ ЖІНОК ТА ДІВЧАТ, ЯКІ ВИЇЖДЖАЮТЬ ЗА КОРДОН', link='https://gormrada.gov.ua/news/1650345226/', publish...
       │    └ <function RssNewsSender.is_unique_news at 0x000002CDEE274160>
       └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

  File "C:\python\core_channel_gor\rsswatch.py", line 83, in is_unique_news
    self.db_cursor.execute(q)
    │    │         │       └ 'SELECT time_publick FROM news WHERE time_publick = 1650345166'
    │    │         └ <method 'execute' of 'sqlite3.Cursor' objects>
    │    └ <sqlite3.Cursor object at 0x000002CDEDF519C0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 14832 and this is thread id 15332.
2022-05-15 15:19:51.196 | ERROR    | rsswatch:execute_rss_news:131 - An error has been caught in function 'execute_rss_news', process 'MainProcess' (14404), thread 'Thread-1 (loop)' (15332):
Traceback (most recent call last):

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002CDEB4341F0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000002CDEB417EB0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    └ <bound method RssNewsSender.loop of <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\python\core_channel_gor\rsswatch.py", line 160, in loop
    self.execute_rss_news()
    │    └ <function RssNewsSender.execute_rss_news at 0x000002CDEE274EE0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

> File "C:\python\core_channel_gor\rsswatch.py", line 131, in execute_rss_news
    if self.is_unique_news(news):
       │    │              └ FeedItem(title='ПРАТ «ЗВЕНИГОРОДСЬКИЙ СИРОРОБНИЙ КОМБІНАТ» ПІДТРИМУЄ ВНУТРІШНЬО ПЕРЕМІЩЕНИХ ОСІБ', link='https://gormrada.gov...
       │    └ <function RssNewsSender.is_unique_news at 0x000002CDEE274160>
       └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

  File "C:\python\core_channel_gor\rsswatch.py", line 83, in is_unique_news
    self.db_cursor.execute(q)
    │    │         │       └ 'SELECT time_publick FROM news WHERE time_publick = 1650287456'
    │    │         └ <method 'execute' of 'sqlite3.Cursor' objects>
    │    └ <sqlite3.Cursor object at 0x000002CDEDF519C0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 14832 and this is thread id 15332.
2022-05-15 15:19:51.305 | ERROR    | rsswatch:execute_rss_news:131 - An error has been caught in function 'execute_rss_news', process 'MainProcess' (14404), thread 'Thread-1 (loop)' (15332):
Traceback (most recent call last):

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002CDEB4341F0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000002CDEB417EB0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    └ <bound method RssNewsSender.loop of <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\python\core_channel_gor\rsswatch.py", line 160, in loop
    self.execute_rss_news()
    │    └ <function RssNewsSender.execute_rss_news at 0x000002CDEE274EE0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

> File "C:\python\core_channel_gor\rsswatch.py", line 131, in execute_rss_news
    if self.is_unique_news(news):
       │    │              └ FeedItem(title='План заходів  щорічної Всеукраїнської акції «За чисте довкілля» на  території населених пунктів Городищенсько...
       │    └ <function RssNewsSender.is_unique_news at 0x000002CDEE274160>
       └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

  File "C:\python\core_channel_gor\rsswatch.py", line 83, in is_unique_news
    self.db_cursor.execute(q)
    │    │         │       └ 'SELECT time_publick FROM news WHERE time_publick = 1649856983'
    │    │         └ <method 'execute' of 'sqlite3.Cursor' objects>
    │    └ <sqlite3.Cursor object at 0x000002CDEDF519C0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 14832 and this is thread id 15332.
2022-05-15 15:19:51.368 | ERROR    | rsswatch:execute_rss_news:131 - An error has been caught in function 'execute_rss_news', process 'MainProcess' (14404), thread 'Thread-1 (loop)' (15332):
Traceback (most recent call last):

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002CDEB4341F0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000002CDEB417EB0>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\Users\38093\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-1 (loop), started 15332)>
    │    └ <bound method RssNewsSender.loop of <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>>
    └ <Thread(Thread-1 (loop), started 15332)>

  File "C:\python\core_channel_gor\rsswatch.py", line 160, in loop
    self.execute_rss_news()
    │    └ <function RssNewsSender.execute_rss_news at 0x000002CDEE274EE0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

> File "C:\python\core_channel_gor\rsswatch.py", line 131, in execute_rss_news
    if self.is_unique_news(news):
       │    │              └ FeedItem(title='ЗАКРІПЛЕННЯ ТЕРИТОРІЙ ЗА ОРГАНІЗАЦІЯМИ, УСТАНОВАМИ, ПІДПРИЄМСТВАМИ ТА СУБ’ЄКТАМИ ПІДПРИЄМНИЦЬКОЇ ДІЯЛЬНОСТІ Н...
       │    └ <function RssNewsSender.is_unique_news at 0x000002CDEE274160>
       └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

  File "C:\python\core_channel_gor\rsswatch.py", line 83, in is_unique_news
    self.db_cursor.execute(q)
    │    │         │       └ 'SELECT time_publick FROM news WHERE time_publick = 1649852113'
    │    │         └ <method 'execute' of 'sqlite3.Cursor' objects>
    │    └ <sqlite3.Cursor object at 0x000002CDEDF519C0>
    └ <rsswatch.RssNewsSender object at 0x000002CDEDBD66B0>

sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 14832 and this is thread id 15332.
